spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/golive
    username: golive
    password: golive

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
